# Generated by Django 4.2 on 2023-04-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(default=str, max_length=120),
            preserve_default=False,
        ),
    ]
